export const ACTION = {
  FETCH_DATA: 'FETCH_DATA',
  CHANGE_DATERANGE: 'CHANGE_DATERANGE',
  RESET_DATERANGE: 'RESET_DATERANGE',
  CHANGE_SINGLEDATE: 'CHANGE_SINGLEDATE',
}


export const MODAL_ACTION = {
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MODAL: 'OPEN_MODAL',
  SET_FAILED_STATUS: 'SET_FAILED_STATUS',
  SET_SUCCESS_STATUS: 'SET_SUCCESS_STATUS',

}